package RouteSolution.RobotWalks;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Dimension;

public class Mars extends JFrame {

  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.drawRect(12, 12, 800, 800);
    }
  };
  public void initialize() {
    this.setTitle("Mars");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(1600, 800));
    this.pack();
    this.setVisible(true);
  }
  public static void main(String[] args) {
    Mars roboteRoute = new Mars();
    roboteRoute.initialize();
  }
}
