package RouteSolution.RobotWalks;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Dimension;

public class Mars extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      Point point = new Point(17, 17);
      int distance = 100;
      int leftDistance = 125;
      Point knownPoint = new Point();



      graphics.drawRect(12, 12, 800, 600);
      knownPoint = moveForward(point, 0, distance, graphics);
      knownPoint = moveForward(point, 0, distance, graphics);
      moveLeft(knownPoint, 1, leftDistance, graphics);
      moveLeft(knownPoint, 1, leftDistance, graphics);

    }
  };
  public void initialize() {
    this.setTitle("Mars");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(1600, 800));
    this.pack();
    this.setVisible(true);
  }
  public static void main(String[] args) {
    Mars roboteRoute = new Mars();
    roboteRoute.initialize();
  }

  public Point moveForward(Point currentPoint, int currentDirec, int distance, Graphics graphics) {
    Point resPoint = new Point();
    resPoint.x = currentPoint.x + distance;
    resPoint.y = currentPoint.y;

    graphics.drawLine(currentPoint.x, currentPoint.y, resPoint.x, resPoint.y);
    return resPoint;
  }

  public Point moveLeft(Point currentPoint, int currentDirec, int distance, Graphics graphics) {
    Point resPoint = new Point();
    resPoint.x = currentPoint.x;
    resPoint.y = currentPoint.y + distance;

    graphics.drawLine(currentPoint.x, currentPoint.y, resPoint.x, resPoint.y);
    return resPoint;
  }

}
