package Route.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Canvas = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Line = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Rectangle = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Shape = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Canvas;
      case 1:
        return props_Line;
      case 2:
        return props_Rectangle;
      case 3:
        return props_Shape;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
