package Route.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(3);
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptRectangle = createDescriptorForRectangle();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptCanvas.getId(), 0);
    myIndexMap.put(myConceptRectangle.getId(), 1);
    myIndexMap.put(myConceptShape.getId(), 2);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptRectangle, myConceptShape);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptCanvas;
      case 1:
        return myConceptRectangle;
      case 2:
        return myConceptShape;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    return new ConceptDescriptorBuilder("Route.structure.Canvas", MetaIdFactory.conceptId(0xa5a3f5242a154733L, 0xb0f02be616993f8dL, 0x3d515f5bd038dcf8L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3d515f5bd038dd62L, "shapes", MetaIdFactory.conceptId(0xa5a3f5242a154733L, 0xb0f02be616993f8dL, 0x3d515f5bd038ddabL), true, true, false, new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217506"))).children(new String[]{"shapes"}, new boolean[]{true}).rootable().alias("Canvas", "").sourceNode(new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217400")).create();
  }
  private static ConceptDescriptor createDescriptorForRectangle() {
    return new ConceptDescriptorBuilder("Route.structure.Rectangle", MetaIdFactory.conceptId(0xa5a3f5242a154733L, 0xb0f02be616993f8dL, 0x3d515f5bd038ddcfL)).super_("Route.structure.Shape").version(1).super_(MetaIdFactory.conceptId(0xa5a3f5242a154733L, 0xb0f02be616993f8dL, 0x3d515f5bd038ddabL)).parents("Route.structure.Shape").parentIds(MetaIdFactory.conceptId(0xa5a3f5242a154733L, 0xb0f02be616993f8dL, 0x3d515f5bd038ddabL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3d515f5bd038de21L, "length", new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217697")), new ConceptDescriptorBuilder.Prop(0x3d515f5bd038de24L, "width", new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217700"))).properties("length", "width").alias("boundary", "").sourceNode(new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217615")).create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    return new ConceptDescriptorBuilder("Route.structure.Shape", MetaIdFactory.conceptId(0xa5a3f5242a154733L, 0xb0f02be616993f8dL, 0x3d515f5bd038ddabL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3d515f5bd038ddcaL, "xPos", new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217610")), new ConceptDescriptorBuilder.Prop(0x3d515f5bd038ddc7L, "yPos", new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217607"))).properties("xPos", "yPos").sourceNode(new SNodePointer("r:64d579f7-caba-44a4-bb25-9e317a59d220(Route.structure)", "4418417557367217579")).create();
  }
}
