package Route.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class Canvas_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_v161ay_a(editorContext, node);
  }
  private EditorCell createCollection_v161ay_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_v161ay_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_v161ay_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_h0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_i0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_v161ay_j0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_v161ay_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "[> Robot walks on Planet {name}:<]");
    editorCell.setCellId("Constant_v161ay_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "[-");
    editorCell.setCellId("Constant_v161ay_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(/");
    editorCell.setCellId("Constant_v161ay_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "%");
    editorCell.setCellId("Constant_v161ay_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "shapes");
    editorCell.setCellId("Constant_v161ay_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "%");
    editorCell.setCellId("Constant_v161ay_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "/)");
    editorCell.setCellId("Constant_v161ay_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "-]");
    editorCell.setCellId("Constant_v161ay_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_i0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "/empty cell:");
    editorCell.setCellId("Constant_v161ay_i0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_v161ay_j0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_v161ay_j0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
