package Route.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;

public class Forward_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_3bxmb7_a(editorContext, node);
  }
  private EditorCell createCollection_3bxmb7_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_3bxmb7_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createComponent_3bxmb7_a0(editorContext, node));
    return editorCell;
  }
  private EditorCell createComponent_3bxmb7_a0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "Route.editor.CommandComp");
    return editorCell;
  }
}
