package Route.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class Rectangle_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_xvcrwe_a(editorContext, node);
  }
  private EditorCell createCollection_xvcrwe_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_xvcrwe_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_xvcrwe_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_h0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_i0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_j0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xvcrwe_k0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "#");
    editorCell.setCellId("Constant_xvcrwe_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "ShapeComp");
    editorCell.setCellId("Constant_xvcrwe_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "#");
    editorCell.setCellId("Constant_xvcrwe_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "length:");
    editorCell.setCellId("Constant_xvcrwe_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_xvcrwe_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "length");
    editorCell.setCellId("Constant_xvcrwe_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_xvcrwe_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "width:");
    editorCell.setCellId("Constant_xvcrwe_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_i0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_xvcrwe_i0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_j0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "width");
    editorCell.setCellId("Constant_xvcrwe_j0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xvcrwe_k0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_xvcrwe_k0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
