package Route.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Collections;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class ShapeComp implements ConceptEditorComponent {
  @NotNull
  public Collection<String> getContextHints() {
    return Collections.emptyList();
  }
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_30er6g_a(editorContext, node);
  }
  private EditorCell createCollection_30er6g_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_30er6g_a");
    editorCell.addEditorCell(this.createConstant_30er6g_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_h0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_i0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_j0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_30er6g_k0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_30er6g_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "#");
    editorCell.setCellId("Constant_30er6g_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "alias");
    editorCell.setCellId("Constant_30er6g_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "#");
    editorCell.setCellId("Constant_30er6g_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "x:");
    editorCell.setCellId("Constant_30er6g_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_30er6g_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "xPos");
    editorCell.setCellId("Constant_30er6g_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_30er6g_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "y:");
    editorCell.setCellId("Constant_30er6g_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_i0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_30er6g_i0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_j0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "yPos");
    editorCell.setCellId("Constant_30er6g_j0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_30er6g_k0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_30er6g_k0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
